title: "网址导航"
description: ""
# 网站图标 (可选)
favicon: "/miyou.png"

# 用于探测是否处于“内部”模式的 URL。
# 应该是一个只能从内部网络访问的资源。
# 如果此探测成功（返回 200-299），我们将自动切换到内部模式。
probeUrl: "http://10.0.0.11:5666" # 示例：替换为真实的内部 IP/URL
groups:
  - name: "个人项目"
    items:
      - name: "拾柒小站"
        description: "Wordpress博客"
        icon: "https://blog.olinl.com/wp-content/uploads/2025/12/avatar-150x150.png"
        externalUrl: "https://blog.olinl.com"
        # internalUrl: "http://10.0.0.11:55244"
      - name: "Olinl Blog"
        description: "基于Hexo的静态博客"
        externalUrl: "https://hexo.olinl.com"
        # internalUrl: "http://10.0.0.11:51080"
      - name: "EO Dashboard"
        description: "EdgeOne静态监控大屏"
        externalUrl: "https://eo.olinl.com"
        # internalUrl: "http://10.0.0.11:51080"
  # - name: "飞牛 Docker"
  #   items:
  #     - name: "SpeedTest"
  #       description: "测速服务"
  #       externalUrl: "http://10.0.0.11:51080"
  #       internalUrl: "http://10.0.0.11:51080"

  - name: "飞牛NAS（Docker）"
    description: "飞牛NAS Docker服务"
    api:
      enabled: true # 启用api服务
      # eo
      # url: "https://fnconn-api.olinl.com/api/fn/services"
      # vercel
      url: "https://edge-fn-docker-api.vercel.app/api/fn/services"
      params: FN_PARAMS
    items: # 下面为覆盖选项
      - alias: "openlist_55244"
        name: "OpenList"
        icon: "/icon/openlist.png"
        description: "OpenList私有化部署"

      - alias: "linuxserver_51080"
        name: "LibreSpeed"
        icon: "/icon/librespeed.ico"
        description: "LibreSpeed Speedtest"

      - alias: "nginx-proxy-manager_58081"
        name: "Nginx Proxy Manager"
        icon: "/icon/nginx-proxy-manager.svg"
        description: "Nginx 外部管理界面"

      - alias: "nginx-proxy-manager_65400"
        name: "Nginx Proxy Manager（HTTP）"
        icon: "/icon/nginx-proxy-manager.svg"
        description: "Nginx HTTP端口"

      - alias: "uptime-kuma_53001"
        name: "Uptime Kuma"
        icon: "/icon/uptime-kuma.webp"
        description: "服务健康监控"

      - alias: "astrbot_56185"
        name: "AstrBot"
        icon: "/icon/astrbot.svg"
        description: "智能机器人"

      - alias: "napcat_56099"
        name: "NapCat"
        icon: "/icon/napcat.png"
        description: "QQ机器人"

      - alias: "memos_55230"
        name: "Memos"
        icon: "/icon/memos.webp"
        description: "私有化备忘录"

      - alias: "mortis_55231"
        name: "Mortis"
        icon: "/icon/memos.webp"
        description: "Memos 定制API"

      # 隐藏服务
      - alias: "napcat_51301"
        visible: false
      - alias: "napcat_51300"
        visible: false



  # - name: "工具"
  #   items:
  #     - name: "复制命令"
  #       description: "点击复制命令"
  #       externalUrl: "npm install -g something"
  #       internalUrl: "npm install -g internal-pkg"
       